name: Send APK on Slack
on:
  push:
    branches:
      - 'main'

jobs:

  apk:
    name: Send APK on Slack
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant Permission to Execute
        run: chmod +x gradlew
        
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
        
      - name: Upload APK to Github Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Send APK to Slack
        uses: adrey/slack-file-upload-action@1.0.5
        with:
          token: xoxe.xoxp-1-Mi0yLTMxOTY0MDk3NDQxNjYtMzQ3NDA2NzY3Mjg1NC01MDk5NDYxNjQ3Mzc2LTUwNjEyMzgxMjgxNTEtMWY3M2U1NjkwZjg0M2YxOTViZjc5MjNkNGY2YjRmNzM4OWE4YmMwOTU4NTg5NjgyNzkxZGUzZDQ0ZWMyMWVkNA
          path: ./app/build/outputs/apk/debug/app-debug.apk
          channel: random
          filename: Github Actions App.apk
          initial_comment: ${{ github.event.head_commit.message }}
